sudo: required

language: c

services:
  - docker

before_install:
- docker pull an4967/tizenrt:1.1
- echo $pwd
- cd ..
- ls
- echo $pwd

script:
- docker run -it --name tizenrt_docker -v $(pwd):/root/tizenrt an4967/tizenrt:1.1 /bin/bash
- docker exec tizenrt_docker ls "./root/tizenrt"
- docker exec tizenrt_docker exit
- echo "Done"