sudo: true
dist: trusty

language: c

services:
- docker

jobs:
	include:
		- stage: Prerequisite
			script: docker pull an4967/tizenrt:1.1
		- script: echo "${TRAVIS_BUILD_DIR}"
		- stage: Build
			env:
				- CONFIG=tash
				- CONFIG=nettest
				- CONFIG=minimal
			script: echo "Build - ${CONFIG}"
		- script: docker run -d -it --name tizenrt_docker -v ${TRAVIS_BUILD_DIR}:/root/tizenrt -w /root/tizenrt/os an4967/tizenrt:1.1 /bin/bash
		- script: docker exec tizenrt_docker make distclean
		- script: docker exec -it tizenrt_docker bash -c "cd tools; ./configure.sh artik053/${CONFIG}"
		- script: docker exec -it tizenrt_docker bash -c "export PATH=/root/gcc-arm-none-eabi-4_9-2015q3/bin:$PATH;make;"
		